name: Avaline
description: A sample command-line application.
version: 0.0.1
# homepage: https://www.example.com
author: Bailey Matthews <Bailey@Bailey.guru>

environment:
  sdk: '>=2.0.0-dev.52.0 <2.0.0'

dependencies:
  millisecond: 0.1.0
  dartsicord: "^0.1.1+1"

dev_dependencies:
  test: ^0.12.30
